[neovim]
src.git = "https://github.com/neovim/neovim"
fetch.github = "neovim/neovim"

[vim]
src.git = "https://github.com/vim/vim"
fetch.github = "vim/vim"

[cchook]
src.git = "https://github.com/syou6162/cchook"
fetch.github = "syou6162/cchook"

[k1Low-deck]
src.git = "https://github.com/k1LoW/deck"
fetch.github = "k1LoW/deck"

[laminate]
src.git = "https://github.com/Songmu/laminate"
fetch.github = "Songmu/laminate"

[gwq]
src.git = "https://github.com/d-kuro/gwq"
fetch.github = "d-kuro/gwq"

[tree-sitter]
src.github_tag = "tree-sitter/tree-sitter"
src.include_regex = "v0.25.10"
fetch.github = "tree-sitter/tree-sitter"

[pict]
src.git = "https://github.com/microsoft/pict"
fetch.github = "microsoft/pict"
